@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package UI <<Rectangle>> {
    Class "<<interface>>\nUi" as Ui
    Class "{abstract}\nUiPart" as UiPart
    Class UiManager
    Class MainWindow
    Class HelpWindow
    Class ResultDisplay
    Class SeniorListPanel
    Class SeniorCard
    Class CaregiverListPanel
    Class CaregiverCard
    Class StatusBarFooter
    Class CommandBox
}

package Model <<Rectangle>> {
    Class HiddenModel #FFFFFF
}

package Logic <<Rectangle>> {
    Class HiddenLogic #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Ui

UiManager .left.|> Ui
UiManager -down-> "1" MainWindow
MainWindow *-down-> "1" CommandBox
MainWindow *-down-> "1" ResultDisplay
MainWindow *-down-> "1" SeniorListPanel
MainWindow *-down-> "1" CaregiverListPanel
MainWindow *-down-> "1" StatusBarFooter
MainWindow --> "0..1" HelpWindow

SeniorListPanel -down-> "*" SeniorCard
CaregiverListPanel -down-> "*" CaregiverCard

MainWindow -left-|> UiPart

ResultDisplay --|> UiPart
CommandBox --|> UiPart
SeniorListPanel --|> UiPart
SeniorCard --|> UiPart
CaregiverListPanel --|> UiPart
CaregiverCard --|> UiPart
StatusBarFooter --|> UiPart
HelpWindow --|> UiPart

SeniorCard ..> Model
CaregiverCard ..> Model
UiManager -right-> Logic
MainWindow -left-> Logic

SeniorListPanel -[hidden]left- CaregiverListPanel
CaregiverListPanel -[hidden]left- HelpWindow
HelpWindow -[hidden]left- CommandBox
CommandBox -[hidden]left- ResultDisplay
ResultDisplay -[hidden]left- StatusBarFooter

MainWindow -[hidden]-|> UiPart
@enduml
